"""empty message

Revision ID: 903b4378a9c0
Revises: eb10da566749
Create Date: 2016-02-13 23:40:28.070325

"""

# revision identifiers, used by Alembic.
revision = '903b4378a9c0'
down_revision = 'eb10da566749'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('khutbahs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mosque_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('is_enforced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosques.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'mosques', sa.Column('imam_id', sa.Integer(), nullable=True))
    op.add_column(u'mosques', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'mosques', 'users', ['imam_id'], ['id'])
    op.add_column(u'topics', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column(u'topics', sa.Column('description', sa.String(), nullable=True))
    op.add_column(u'topics', sa.Column('status', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'topics', 'status')
    op.drop_column(u'topics', 'description')
    op.drop_column(u'topics', 'date_added')
    op.drop_constraint(None, 'mosques', type_='foreignkey')
    op.drop_column(u'mosques', 'is_active')
    op.drop_column(u'mosques', 'imam_id')
    op.drop_table('khutbahs')
    ### end Alembic commands ###
